### ISSUE TITLE
Audio crash issue

### ISSUE THREAD

**Issue by GR8GH** [Erfaniom/Erfaniom#1]
Seems like the string for the "**Bruh Sound effect** " is causing crashes

I recommend cutting the string entirely since it serves no purpose other than playing the Sound effect

**Comment by Erfaniom** [comment]
it works fine for me

and the entire reason this plugin exists is for bruh sound effect if i cut the string im gonna have to delete this repo
so yeah, youre gay
*sick guitar solo*
